
spring:
  application:
    name: eureka-provider

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka, http://peer2:2222/eureka

#    status-page-url: http://${eureka.instance.hostname}/info
#    health-check-url: http://${eureka.instance.hostname}/health
#    home-page-url: http://${eureka.instance.hostname}/

---
server:
  port: 8081
spring:
  profiles: provider1
---
server:
  port: 8082
spring:
  profiles: provider2