
spring:
  application:
    name: eureka-consumer

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:1111/eureka, http://peer2:2222/eureka
  instance:
    hostname: localhost
